<?php
	/* ROUTER TEMPLATE
      USED FOR FOR WHEN PAGES DON'T MATTER BUT THE CHILDREN DO SOMETHING
      SUCH AS EDIT/ORDERS/ EDIT ITSELF DOESN'T MATTER, BUT EDIT/ORDERS/ IS SOMETHING


    */
    throw new Wire404Exception();
?>
